# Generated by Django 4.2.5 on 2023-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', 'backfill_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.CharField(default='This restaurant is good :^)', max_length=255),
        ),
    ]
