# Generated by Django 4.2.5 on 2023-11-09 21:27

from django.db import migrations

def populate_image_num(apps, schema_editor):
    Restaurant = apps.get_model('RestaurantApp', 'Restaurant')
    restaurants = Restaurant.objects.all()
    for i, restaurant in enumerate(restaurants, start=1):
        number = i % 17 if i % 17 != 0 else 17
        restaurant.imageNum = f"/rectangle-404{number}@2x.png"
        restaurant.save(update_fields=['imageNum'])

class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0001_restaurant_imagenum'),
    ]

    operations = [
        migrations.RunPython(populate_image_num),
    ]
