# Generated by Django 4.2.5 on 2023-10-07 20:23

from django.db import migrations
import csv

from ..models import Restaurant

COUNTRY_CODE_MAP = {
    '1' : 'India',
    '14' : 'Australia',
    '30' : 'Brazil',
    '37' : 'Canada',
    '94' : 'Indonesia',
    '148' : 'New Zealand',
    '162' : 'Phillipines',
    '166' : 'Qatar',
    '184' : 'Singapore',
    '189' : 'South Africa',
    '191' : 'Sri Lanka',
    '208' : 'Turkey',
    '214' : 'UAE',
    '215' : 'United Kingdom',
    '216' : 'United State'
}

def create_restaurant(row):
    Restaurant.objects.create(
        name = row['Restaurant Name'],
        country = COUNTRY_CODE_MAP[row['Country Code']],
        city = row['City'],
        address = row['Address'],
        longitude = float(row['Longitude']),
        latitude = float(row['Latitude']),
        cuisines = row['Cuisines'],
        average_cost_for_two = int(row['Average Cost for two']),
        average_review_rating = float(row['Aggregate rating']),
        review_level_color = row['Rating color'],
        review_level_text = row['Rating text'],
        number_of_reviews = int(row['Votes'])
    )

def backfill_restaurant_data():
    with open ('data/restaurant_data.csv') as file_data:
        reader = csv.DictReader(file_data)
        for row in reader:
            create_restaurant(row)

    

class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_restaurant_data)
    ]
