# Generated by Django 4.2.5 on 2023-10-07 20:23

from django.db import migrations
import csv

COUNTRY_CODE_MAP = {
    '1' : 'India',
    '14' : 'Australia',
    '30' : 'Brazil',
    '37' : 'Canada',
    '94' : 'Indonesia',
    '148' : 'New Zealand',
    '162' : 'Phillipines',
    '166' : 'Qatar',
    '184' : 'Singapore',
    '189' : 'South Africa',
    '191' : 'Sri Lanka',
    '208' : 'Turkey',
    '214' : 'UAE',
    '215' : 'United Kingdom',
    '216' : 'United State'
}

def form_restaurant(row, Restaurant):
    return Restaurant(
        name = row['Restaurant Name'],
        country = COUNTRY_CODE_MAP[row['Country Code']],
        city = row['City'],
        address = row['Address'],
        longitude = float(row['Longitude']),
        latitude = float(row['Latitude']),
        cuisines = row['Cuisines'],
        average_cost_for_two = int(row['Average Cost for two']),
        average_review_rating = float(row['Aggregate rating']),
        review_level_color = row['Rating color'],
        review_level_text = row['Rating text'],
        number_of_reviews = int(row['Votes'])
    )

def form_restaurants(Restaurant):
    formed_restaurants = []
    with open ('RestaurantApp/migrations/data/restaurant_data.csv') as file_data:
        reader = csv.DictReader(file_data)
        for row in reader:
            formed_restaurants.append(form_restaurant(row, Restaurant))
    return formed_restaurants

def backfill_restaurant_data(apps, schema_editor):
    Restaurant = apps.get_model('RestaurantApp', 'Restaurant')
    db_alias = schema_editor.connection.alias

    restaurants_to_add = form_restaurants(Restaurant)

    
    Restaurant.objects.using(db_alias).bulk_create(restaurants_to_add)

    

class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_restaurant_data)
    ]
